{% set name = "fcswrite" %}
{% set version = "0.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/fcswrite-{{ version }}.tar.gz
  sha256: 58a75e84e3f79775dc3d96a8df5805d9b0225bc5d843892f61a633a3ad9303d8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - pytest-runner
    - python >=3.6
  run:
    - numpy >=1.7.0
    - python >=3.6

test:
  imports:
    - fcswrite
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ZELLMECHANIK-DRESDEN/fcswrite
  summary: Write .fcs files (flow cytometry)
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
